apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  selector:
    matchLabels:
      app: odf-console
  template:
    metadata:
      labels:
        app: odf-console
    spec:
      containers:
        - name: odf-console
          image: odf-console:latest
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
          ports:
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: odf-console-serving-cert
              mountPath: /var/serving-cert
              readOnly: true
      volumes:
        - name: odf-console-serving-cert
          secret:
            secretName: odf-console-serving-cert
